mv ../byfn.sh ../byfn.sh.original
cp byfn.sh.multiOrg ../byfn.sh
mv ../ccp-generate.sh ../ccp-generate.sh.original
cp ccp-generate.sh.multiOrg ../ccp-generate.sh
mv ../configtx.yaml ../configtx.yaml.original
cp configtx.yaml.multiOrg ../configtx.yaml
mv ../crypto-config.yaml ../crypto-config.yaml.original
cp crypto-config.yaml.multiOrg ../crypto-config.yaml
mv ../base/docker-compose-base.yaml ../base/docker-compose-base.yaml.original
cp docker-compose-base.yaml.multiOrg ../base/docker-compose-base.yaml
mv ../scripts/script.sh ../scripts/script.sh.original
cp script.sh.multiOrg ../scripts/script.sh
mv ../scripts/utils.sh ../scripts/utils.sh.original
cp utils.sh.multiOrg ../scripts/utils.sh
